# -*- coding: utf-8 -*-
"""cyberlaw mapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16kFS-ry3zVXZhmQE8n0K05SHjILXiuL_
"""

from textblob import TextBlob

with open('sex_keywords.txt', 'r') as f:
    explicit_keywords = [line.strip() for line in f]

comment = "You look pretty today, but I think your outfit would look better if it was tighter."

blob = TextBlob(comment)

polarity = blob.sentiment.polarity

explicit_count = sum(keyword in comment.lower() for keyword in explicit_keywords)

if explicit_count > 0 and polarity < -0.5:
    print('This comment is sexually harassed and negative.Section 354A (sexual harassment), and Section 509 (word, gesture or act intended to insult the modesty of a woman). ')
#elif explicit_count > 0:
    #print('This comment is sexually harassed.')
elif polarity < -0.5:
    print('This comment is negative.Section 354A ')
else:
    print('This comment is not sexually harassed. ')

